### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by geekplux** [jxnblk/mdx-deck#108]
Below error will report if `babel-core` not installed.

```bash
$ npm start

> @ start /Users/ppt
> mdx-deck deck.mdx

[mdx-deck] starting dev server
✖ ｢wdm｣:
ERROR in ./node_modules/_mdx-deck@1.6.0@mdx-deck/dist/entry.js
Module build failed (from ./node_modules/_babel-loader@7.1.5@babel-loader/lib/index.js):
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/geekplux/project/ppt/node_modules/_babel-loader@7.1.5@babel-loader/lib/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
 @ multi ./node_modules/_mdx-deck@1.6.0@mdx-deck/dist/entry.js ./node_modules/_mdx-deck@1.6.0@mdx-deck/lib/overlay.js main[0]
```
looks like should add `babel-core` into devDependencies. 🌞

**Comment by iamgrawal** [comment]
Created a pull request for that, hope it will be merged soon 😃. 
Meanwhile, you can explicitly add babel-core dependency into your project by typing: ```npm install --save-dev babel-core```.
