### ISSUE TITLE
Using `withDeck` HOC from installed module throws error during `mdx-deck build`

### ISSUE THREAD

**Issue by jesstelford** [jxnblk/mdx-deck#171]
For a minimal reproduction, see: https://gist.github.com/jesstelford/368df55ea20d239234dd28282b7789ed

In this case, it's `mdx-deck-code-surfer` erroring with:

```
$ mdx-deck build index.mdx
[mdx-deck] building
[mdx-deck] rendering static html
[err] TypeError: Cannot read property 'update' of null
    at new InnerCodeSurfer (node_modules/mdx-deck-code-surfer/dist/deck-code-surfer.js:60:30)
    at processChild (node_modules/react-dom/cjs/react-dom-server.node.development.js:2418:14)
    at resolve (node_modules/react-dom/cjs/react-dom-server.node.development.js:2384:5)
    at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:2706:22)
    at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:2680:23)
    at renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:3071:25)
    at renderHTML (node_modules/mdx-deck/lib/html.js:65:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by programbo** [comment]
This is affecting me, too. Does no one else using `mdx-deck-code-surfer` run the build step? Something is going on with the React context and `deck` is not being set when it is supposed to be.

**Comment by jxnblk** [comment]
The `withDeck` HOC has been replaced with `useSteps` in v2. I'll be adding some docs for that soon
