### ISSUE TITLE
Can't npm start - destructured props - Unexpected token ... 

### ISSUE THREAD

**Issue by jagretz** [jxnblk/mdx-deck#184]
This is odd, and I don't think it's a bug but i am receiving an error when trying to start mdx-deck and am having trouble finding a solution.

 It appears node is having trouble with destructuring syntax. 
[EDIT] I did make sure the version of node I'm using supports this syntax before opening the ticket.

This is a fresh install of mdx-deck in a new git project and I've already removed and reinstalled mdx-deck from npm and received the same error.

**Code in question...** `node_modules\@mdx-js\mdx\mdx-hast-to-jsx.js:21`

```js
    node.properties = Object.entries(node.properties).reduce((properties, [key, value]) => ({
      ...properties,
      [paramCaseRe.test(key) ? paramCase(key) : key]: value,
    }), {})
```

**Error**

```bash
mdx-deck deck.mdx "-p" "3100"

[mdx-deck] starting dev server
× ｢wdm｣:
ERROR in ./deck.mdx
Module build failed (from ./node_modules/mdx-deck/lib/loader.js):
\node_modules\@mdx-js\mdx\mdx-hast-to-jsx.js:21
      ...properties,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (\node_modules\@mdx-js\mdx\index.js:6:22)
 @ ./node_modules/mdx-deck/dist/entry.js 65:10-27
 @ multi ./node_modules/mdx-deck/dist/entry.js ./node_modules/mdx-deck/lib/overlay.js
[mdx-deck] listening on http://127.0.0.1:3100
```
**meta info**

```bash
Windows 10 (i can get the version if necessary)
node -v v8.2.1
npm -v 5.3.0
npm list mdx-deck
`-- mdx-deck@1.7.7
```

**Comment by jagretz** [comment]
Works fine using node v10.50 npm v6.1.0
It's possible the installation of node 8.2.1 messed up, or... maybe a minor issue with that version of node.  I'll have to test this on another windows 10 machine tomorrow.

**Comment by jagretz** [comment]
I had a co-worker try this on his Mac and ran into the same issue. I'll assume this is a problem with version node 8.2.1 and leave it at that.

I found [this issue in the 8.3.0 changelog](https://github.com/nodejs/node/pull/14467) which points to [this line](https://github.com/nodejs/node/commit/1a5927fc27#diff-293fefe850253c8c28e2481c0b7f76e2R418).

Maybe that was the problem. Eitherway, i can use a different version of node for this project. Cheers
