### ISSUE TITLE
Build does not work (apparently if you use CodeSurfer)

### ISSUE THREAD

**Issue by JJ** [jxnblk/mdx-deck#225]
On [this presentation](https://github.com/JJ/git-push) I am trying to get a static version to deploy using:

     node node_modules/mdx-deck/cli.js build

However, this bails out with this error:

```
webpack:///./node_modules/mdx-deck/dist/entry.js?:65
var mod = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '/home/jmerelo/Presentaciones/repo/git-push/build'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                                                           ^

Error: Cannot find module '/home/jmerelo/Presentaciones/repo/git-push/build'
    at webpackMissingModule (webpack:///./node_modules/mdx-deck/dist/entry.js?:65:75)
    at eval (webpack:///./node_modules/mdx-deck/dist/entry.js?:65:198)
    at Object../node_modules/mdx-deck/dist/entry.js (/home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:359:1)
    at __webpack_require__ (/home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:30:30)
    at /home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:94:18
    at /home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:97:10
    at webpackUniversalModuleDefinition (/home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:3:20)
    at Object.<anonymous> (/home/jmerelo/Presentaciones/repo/git-push/dist/TEMP/App.js:10:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

Any idea? `npm start` works perfectly.

**Comment by jxnblk** [comment]
Sorry for the delay, not sure what was going on here, but both MDX Deck and Code Surfer have changed a bit since this was opened. If you're still having issues with the latest versions, please feel free to open a new issue
