### ISSUE TITLE
Build fails since 1.8.1

### ISSUE THREAD

**Issue by jollytoad** [jxnblk/mdx-deck#232]
The static build seems to fail following the 1.8.1 release, 1.8.0 is fine...

```
$ mdx-deck build deck.mdx
[mdx-deck] building
[mdx-deck] rendering static html
[err] ReferenceError: window is not defined
    at Appear.render (webpack:///./node_modules/mdx-deck/dist/Appear.js?:98:7)
    at processChild (/Users/mgibson/decks/state-battle/node_modules/react-dom/cjs/react-dom-server.node.development.js:2861:18)
    at resolve (/Users/mgibson/decks/state-battle/node_modules/react-dom/cjs/react-dom-server.node.development.js:2714:5)
    at ReactDOMServerRenderer.render (/Users/mgibson/decks/state-battle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3098:22)
    at ReactDOMServerRenderer.read (/Users/mgibson/decks/state-battle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3057:29)
    at renderToString (/Users/mgibson/decks/state-battle/node_modules/react-dom/cjs/react-dom-server.node.development.js:3524:27)
    at renderHTML (/Users/mgibson/decks/state-battle/node_modules/mdx-deck/lib/html.js:65:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error Command failed with exit code 1.
```

**Comment by jollytoad** [comment]
Most probably due to the use of 'window' global here...

https://github.com/jxnblk/mdx-deck/commit/cc142d16edf42098e0dc54764c63e93e106c6232
