### ISSUE TITLE
Build fails when using syntax highlight

### ISSUE THREAD

**Issue by gillchristian** [jxnblk/mdx-deck#257]
I get this error when trying to build.

```
$ mdx-deck build deck.mdx -d docs
[mdx-deck] building
[mdx-deck] rendering static html
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'react-syntax-highlighter/prism-light'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at eval (webpack:///external_%22react-syntax-highlighter/prism-light%22?:1:18)
    at Object.react-syntax-highlighter/prism-light (/home/gillchristian/dev/workshops/pattern-matching/docs/TEMP/App.js:913:1)
    at __webpack_require__ (/home/gillchristian/dev/workshops/pattern-matching/docs/TEMP/App.js:30:30)
    at eval (webpack:///./node_modules/mdx-deck/dist/Code.js?:31:19)
    at Object../node_modules/mdx-deck/dist/Code.js (/home/gillchristian/dev/workshops/pattern-matching/docs/TEMP/App.js:191:1)
    at __webpack_require__ (/home/gillchristian/dev/workshops/pattern-matching/docs/TEMP/App.js:30:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This are my dependencies:

```json
"dependencies": {
  "mdx-deck": "^1.6.7",
  "react-syntax-highlighter": "^10.1.2",
  "serve": "^10.1.2",
  "styled-components": "^4.1.3"
}
```

And the `theme.js` file:

```
import { book as theme } from "mdx-deck/themes";

import style from "react-syntax-highlighter/styles/prism/darcula";

import rust from "react-syntax-highlighter/languages/prism/rust";
import go from "react-syntax-highlighter/languages/prism/go";
import csharp from "react-syntax-highlighter/languages/prism/csharp";
import scala from "react-syntax-highlighter/languages/prism/scala";
import elm from "react-syntax-highlighter/languages/prism/elm";
import haskell from "react-syntax-highlighter/languages/prism/haskell";
import reason from "react-syntax-highlighter/languages/prism/reason";
import css from "react-syntax-highlighter/languages/prism/css";
import typescript from "react-syntax-highlighter/languages/prism/typescript";

export default {
  ...theme,
  prism: {
    style,
    languages: {
      rust,
      go,
      csharp,
      scala,
      elm,
      haskell,
      reason,
      css,
      typescript
    }
  },
};
```

I haven't found a solution yet. Will post it if I do.

Code is here: https://github.com/housinganywhere/pattern-matching-ts

**Comment by gillchristian** [comment]
Removed `react-syntax-highlighter` dependency and now it works!

**Comment by LuisReinoso** [comment]
Are you sure that removed `react-syntax-highlighter` dependency mdx-deck works?. Because I have the same problem.
