### ISSUE TITLE
Is there an option to skip a slide?

### ISSUE THREAD

**Issue by vlsi** [jxnblk/mdx-deck#283]
What if I have a half-backed slide which I don't want to show yet?
It would be nice to have something like `export default SkipSlide` (or something like that)

**Comment by jxnblk** [comment]
You should be able to use HTML comments in MDX to comment out parts that you do not want to display

**Comment by vlsi** [comment]
I was not able to comment the whole slide (I use `"mdx-deck": "^1.10.2"`)

**Comment by vlsi** [comment]
For instance, 

```

---

Test

<!--
---

JFR
-->
```

produces


```
ERROR in ./deck.mdx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: .../deck.mdx: Unexpected token (79:1)

  77 |
  78 | ({ components, ...props }) => <MDXTag name="wrapper"  components={components}><MDXTag name="p" components={components}>{`Test`}</MDXTag>
> 79 | <!--</MDXTag>,
     |  ^
  80 |
  81 | ({ components, ...props }) => <MDXTag name="wrapper"  components={components}><MDXTag name="p" components={components}>{`JFR
  82 | -->`}</MDXTag></MDXTag>,
    at Object.raise (.../node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (.../node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.jsxParseIdentifier (.../node_modules/@babel/parser/lib/index.js:3332:12)
    at Object.jsxParseNamespacedName (.../node_modules/@babel/parser/lib/index.js:3342:23)
    at Object.jsxParseElementName (.../node_modules/@babel/parser/lib/index.js:3353:21)
    at Object.jsxParseOpeningElementAt (.../node_modules/@babel/parser/lib/index.js:3438:22)
    at Object.jsxParseElementAt (.../node_modules/@babel/parser/lib/index.js:3471:33)
    at Object.jsxParseElementAt (.../node_modules/@babel/parser/lib/index.js:3487:32)
    at Object.jsxParseElement (.../node_modules/@babel/parser/lib/index.js:3540:17)
    at Object.parseExprAtom (.../node_modules/@babel/parser/lib/index.js:3547:19)
```

**Comment by jxnblk** [comment]
Right, that would require a newer version of mdx. I don't think there's a way to comment or skip a slide with mdx-deck 1

**Comment by vlsi** [comment]
Is there a way to comment a slide with mdx-deck 2?
I've updated to mdx-deck 2, however commenting a slide creates just empty slide:

```
---

Test

<!--

---

JFR

-->

---

...
```

I guess something like `#---` or `export hidden=true` would be great.

**Comment by vlsi** [comment]
Thanks for mdx-deck, it looks like the project is not suitable for presentations on stage: https://github.com/jxnblk/mdx-deck/pull/293
