### ISSUE TITLE
Cannot create as TypeComposer the following value: Date

### ISSUE THREAD

**Issue by keita-makino** [jxnblk/mdx-deck#483]
I got this error when I run `npm-deck`.

``` node
C:\Users\[user]\src\[user]\[project]>npm run deck

> [project]@0.1.0 deck C:\Users\[user]\src\[user]\[project]
> mdx-deck deck.mdx

info Deleting .cache, public
info Successfully deleted directories

success open and validate gatsby-configs - 0.117 s
success load plugins - 2.322 s
success onPreInit - 0.079 s
success initialize cache - 0.072 s
success copy gatsby files - 0.449 s
success onPreBootstrap - 0.100 s
success source and transform nodes - 1.041 s

 ERROR 

UNHANDLED REJECTION Cannot create as TypeComposer the following value: Date.



  Error: Cannot create as TypeComposer the following value: Date.

  - SchemaComposer.js:365 SchemaComposer.createTempTC
    [[project]]/[graphql-compose]/lib/SchemaComposer.js:365:11

  - SchemaComposer.js:563 SchemaComposer.addAsComposer
    [[project]]/[graphql-compose]/lib/SchemaComposer.js:563:27

  - schema-composer.js:35 createSchemaComposer
    [[project]]/[gatsby]/dist/schema/schema-composer.js:35:18

  - index.js:65 Object.module.exports.build
    [[project]]/[gatsby]/dist/schema/index.js:65:26


⠋ building schema
Error: Command failed with exit code 1 (Unknown system error -1): gatsby develop --host localhost --port 8000 --open
    at makeError (C:\Users\[user]\src\[user]\[project]\node_modules\mdx-deck\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\[user]\src\[user]\[project]\node_modules\mdx-deck\node_modules\execa\index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [project]@0.1.0 deck: `mdx-deck deck.mdx`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [project]@0.1.0 deck script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2019-09-18T20_31_15_556Z-debug.log
```

The mdx is just
``` mdx
# Header

hoge
```

What does this mean?  
I set up the project using CRA. I will provide if additional information is needed.

EDIT: I have a dependency on `graphql: 14.4.2` which seems causing this issue according to [this thread](https://github.com/gatsbyjs/gatsby/issues/13278).

**Comment by jxnblk** [comment]
Not sure what the error is, but MDX Deck is meant to either be run on its own as a CLI or as a Gatsby theme. It is not compatible with create-react-app

**Comment by keita-makino** [comment]
I have resolved the issue with deleting `node_modules` and `package-lock.json` and then reinstall the packages.  
Still there is an error though, the issue is gone now.
