### ISSUE TITLE
Generating SSR bundle failed due to Unexpected token

### ISSUE THREAD

**Issue by keita-makino** [jxnblk/mdx-deck#485]
I have the following deck.mdx and Plot.tsx

``` mdx
import Plot from '../components/Plot.tsx';

# Title

hoge
```

``` typescript
// import packages

export interface PlotDataProps { // this is row 18
  index: number;
  x: string;
  y: string;
  z: string;
}


export interface PlotProps {
  axis: {
    x: {
      name: string;
      type: string;
...
```

Then. `npm run deck` will yield

``` node
...
success write out redirect data - 0.092 s
success onPostBootstrap - 0.083 s
⠀
info bootstrap finished - 9.593 s
⠀
success run static queries - 0.072 s
success run page queries - 0.113 s — 3/3 83.31 queries/second

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (18:7)

File: ..\..\src\components\Plot.tsx:18:7

⠇ start webpack server
Error: Command failed with exit code 1 (Unknown system error -1): gatsby develop --host localhost --port 8000 --open
    at makeError (C:\Users\[user]\src\[user]\[project]\node_modules\mdx-deck\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\[user]\src\[user]\[project]\node_modules\mdx-deck\node_modules\execa\index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [project]@0.1.0 deck: `mdx-deck src/documents/deck.mdx`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [project]@0.1.0 deck script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2019-09-20T23_11_03_984Z-debug.log
```

it seems the error is caused by the line exporting the interface, but how to resolve it?

My environment is

| package                    | version         |
| -------------------------- | --------------- |
| OS                         | Windows 10 1903 |
| `mdx-deck`                 | `^3.0.11`       |
| `gatsby`                   | `^2.15.19`      |
| `gatsby-plugin-typescript` | `^2.1.9`        |
| `gatsby-theme-mdx-deck`    | `^3.0.11`       |

``` javascript
module.exports = {
  plugins: [`gatsby-plugin-typescript`]
};
```

**Comment by karlhorky** [comment]
Potentially related (similar error): #640
