### ISSUE TITLE
Upgrading to 3.1.0 without new Gatsby resolution causes error

### ISSUE THREAD

**Issue by karlhorky** [jxnblk/mdx-deck#640]
Upgrading to `3.1.0` (from #631) without upgrading the transitive Gatsby dependency (manually via a resolution) as well causes an error ("unexpected token" => untranspiled JSX).

I would suggest a possible fix with #603.

Log file:

```
info bootstrap finished - 23.376 s
⠀
success run queries - 0.067s - 3/3 44.62/s

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (4:48)

File: ../../../../node_modules/gatsby-theme-mdx-deck/src/index.js:4:48


————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
3 pages                                                                                         In Progress                                                                                         mdx-deck
Error: Command failed with exit code 1: gatsby develop --host localhost --port 8000 --open
    at makeError (./presentations/standard-deck/node_modules/execa/lib/error.js:56:11)
    at handlePromise (./presentations/standard-deck/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Comment by karlhorky** [comment]
**Workaround:** Upgrade all of your packages to use `mdx-deck@3.1.0`, and make sure that you don't have any older versions in your lockfile anymore.

**Comment by jxnblk** [comment]
The core `mdx-deck@3.1.0` requires `gatsby-theme-mdx-deck` `^3.1.0` -- if you're using yarn, I'd recommend using `yarn upgrade-interactive` to make sure it properly updates all the dependencies

**Comment by karlhorky** [comment]
@jxnblk Yes, it upgraded that dependency as well, in the `node_modules` of the workspace:

- `gatsby-theme-mdx-deck@3.1.0` -> `/packages/standard-deck/node_modules/gatsby-theme-mdx-deck`
- `gatsby-theme-mdx-deck@3.0.13` -> `/node_modules/gatsby-theme-mdx-deck`

Something in the module resolution of `mdx-deck` is causing the project's `node_modules` version (the `3.0.13` version) to be used.
