### ISSUE TITLE
Package exports for clipboardy do not define a '.' subpath

### ISSUE THREAD

**Issue by stolinski** [jxnblk/mdx-deck#701]
Getting this 
```
/Users/scotttolinski/Sites/presentations/css/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Package exports for '/Users/scotttolinski/Sites/presentations/css/node_modules/clipboardy' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/scotttolinski/Sites/presentations/css/node_modules/gatsby-cli/lib/create-cli.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10) {
  code: 'MODULE_NOT_FOUND'
}
Error: Command failed with exit code 7: gatsby clean
    at makeError (/Users/scotttolinski/Sites/presentations/css/node_modules/mdx-deck/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/scotttolinski/Sites/presentations/css/node_modules/mdx-deck/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async gatsby (/Users/scotttolinski/Sites/presentations/css/node_modules/mdx-deck/cli.js:65:3)
error Command failed with exit code 1.
```
When using the /example/basic 

Not sure what's going on, my package.json is the same and basic, my deck.mdx is copy and pasted directly.

**Comment by stolinski** [comment]
This was fixed by downgrading node to v12

**Comment by flavienbwk** [comment]
> This was fixed by downgrading node to v12

Or upgrading to v14 !
