### ISSUE TITLE
Can't start mdx-deck on localhost

### ISSUE THREAD

**Issue by raymonschouwenaar** [jxnblk/mdx-deck#764]
Since yesterday I get this error when I try to do `npm start`.

I'm using Windows 10, my editor is Visual Studio Code. Node version is 15.0.1, npm version is.

My repo is here: https://github.com/DevByRayRay/jam-stack-meetup-nov-2020

```
success Building development bundle - 19.960s
error ENOENT: no such file or directory, open 'C:\Users\username\project\mdx-deck\node_modules\mdx-deck\.cache\json\_.json'


  Error: ENOENT: no such file or directory, open 'C:\Users\username\project\mdx-deck  \node_modules\mdx-deck\.cache\json\_.json'
```

**Comment by raymonschouwenaar** [comment]
In Netlify during building I get this error:

```
10:53:26 AM: error There was a problem parsing "/opt/build/repo/deck.mdx"; any GraphQL
10:53:26 AM: fragments or queries in this file were not processed.
10:53:26 AM: This may indicate a syntax error in the code, or it may be a file type
10:53:26 AM: that Gatsby does not know how to parse.
10:53:26 AM: failed extract queries from components - 0.124s
10:53:27 AM: Error: Command failed with exit code 1: gatsby build
10:53:27 AM:     at makeError (/opt/build/repo/node_modules/execa/lib/error.js:59:11)
10:53:27 AM:     at handlePromise (/opt/build/repo/node_modules/execa/index.js:114:26)
10:53:27 AM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
10:53:27 AM: npm ERR! code ELIFECYCLE
10:53:27 AM: npm ERR! errno 1
10:53:27 AM: npm ERR! sv-jamstack-meetup-nov-2020@1.0.0 build: `npx mdx-deck build deck.mdx`
10:53:27 AM: npm ERR! Exit status 1
10:53:27 AM: npm ERR!
10:53:27 AM: npm ERR! Failed at the sv-jamstack-meetup-nov-2020@1.0.0 build script.
10:53:27 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10:53:27 AM: npm ERR! A complete log of this run can be found in:
10:53:27 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-25T09_53_27_059Z-debug.log
10:53:27 AM: ​
10:53:27 AM: ────────────────────────────────────────────────────────────────
10:53:27 AM:   "build.command" failed                                        
10:53:27 AM: ────────────────────────────────────────────────────────────────
10:53:27 AM: ​
10:53:27 AM:   Error message
10:53:27 AM:   Command failed with exit code 1: npm run build
10:53:27 AM: ​
10:53:27 AM:   Error location
10:53:27 AM:   In Build command from Netlify app:
10:53:27 AM:   npm run build
10:53:27 AM: ​
10:53:27 AM:   Resolved config
10:53:27 AM:   build:
10:53:27 AM:     command: npm run build
10:53:27 AM:     commandOrigin: ui
10:53:27 AM:     publish: /opt/build/repo/public
```

But I can't find the syntax error in the `deck.mdx` file :-(
